import type { Metadata } from "next";
import "@/styles/main.scss";
import AnnouncememtBar from "@/ui/components/AnnouncememtBar";
import { Toaster } from "sonner";
import Footer from "@/ui/layouts/Footer";
import Header from "@/ui/layouts/Header";
import { grotestFont, ubuntuFont } from "@/ui/fonts";
import ScrollToTop from "@/ui/components/ScrollToTop";

export const metadata: Metadata = {
  title: "Sephduema | Home",
  description: "Generated by create next app",
  keywords: ['shop', 'online']
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${grotestFont.variable} ${ubuntuFont.variable}`}>
      <body>
        <Toaster richColors position="top-right" />
        <AnnouncememtBar />
        <Header />
        <ScrollToTop />
        <main style={{ minHeight: "200dvh"}}>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
