import type { Metadata } from "next";
import "@/styles/main.scss";
import AnnouncememtBar from "@/ui/components/AnnouncememtBar";
import { Toaster } from "sonner";
import Footer from "@/ui/layouts/Footer";
import Header from "@/ui/layouts/Header";
import { grotestFont, ubuntuFont } from "@/ui/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${grotestFont.variable} ${ubuntuFont.variable}`}>
      <body>
        <Toaster richColors position="top-right" />
        <AnnouncememtBar />
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
